version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mini_twitter.settings
      - PYTHONPATH=/usr/src/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: mini_twitter_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
